[project]
name = "applocker"
version = "1.1.1"
description = "AppLocker Policy parser and emitter for Python"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.11.2",
]
